### ISSUE TITLE
What data is used in your sourcecode?  Could you provide the data you used? Thanks

### ISSUE THREAD

**Issue by guyucowboy** [akashxg/Mammogram-Image-Classifier#1]
Hi, akashxg:
    Great work! Thanks for sharing your codes. I have a question to ask you. What data is used in your sourcecode?  I found the the code extensions = ['jpg', 'jpeg', 'JPG', 'JPEG'] in the function create_image_lists in retain.py which indicated the data format is jpg. But I download the DDSM data as you said, the data format of the DDSM is LJPEG. 
    Could you provide the data you used? Thanks a lot!
Best regards
                                       Gu Yu

**Comment by akashxg** [comment]
Hey Gu Yu:

I used software to convert the LJPEG images into a JPG format. 
Here are the images that I used: https://www.dropbox.com/s/zj0pg2pymir7dji/mammogram_photos.zip?dl=0

Best,
Akash

**Comment by guyucowboy** [comment]
Hi, akashxg:
      I have downloaded your images. Thank you very much!
      I have another question to ask you. What does "bottleneck values for training images" mean? Is there the documention for the project in detail?
      Thanks again.
Best regards
Gu Yu

**Comment by akashxg** [comment]
Bottlenecks are the layers in a network, in this case the ImageNet model, that compress feature representations to best fit in the available space.

Check out this tutorial & this doc:
https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#3

http://www.cs.unc.edu/~wliu/papers/GoogLeNet.pdf

Best,
Akash
